version: "3"
services: 
  mongoDB:
    image: mongo:4.4.1
    container_name: "mongoDB"
    ports:
      - 27017:27017   
  spring:
    image: spring-image
    ports:
      - 8080:8080
    links:
      - mongoDB

